services:
  postgres:
    image: postgres:16-alpine
    container_name: miaumigo-postgres
    environment:
      POSTGRES_DB: miaumigo
      POSTGRES_USER: miaumigo
      POSTGRES_PASSWORD: miaumigo
    ports:
      - "5432:5432"
    volumes:
      - miaumigo-postgres-data:/var/lib/postgresql/data

volumes:
  miaumigo-postgres-data:
