package com.Miaumigo.Miaumigo.domain;

public enum Tag {
	DOCIL,
	BRINCALHAO,
	CALMO,
	INDEPENDENTE,
	CARINHOSO,
	SOCIAL,
	PROTETOR,
	ENERGICO,
	ADAPTADO_A_APARTAMENTO,
	PRECISA_DE_ESPACO,
	CONVIVE_COM_CRIANCAS,
	CONVIVE_COM_CAES,
	CONVIVE_COM_GATOS
}
