import {
  Cat,
  Dog,
  HandHeart,
  Heart,
  Home as HomeIcon,
  MapPin,
  PawPrint,
  Users,
} from "lucide-react";

export const petCategories = [
  { label: "Cachorros", icon: Dog },
  { label: "Gatos", icon: Cat },
  { label: "Filhotes", icon: PawPrint },
  { label: "Próximos de você", icon: MapPin },
  { label: "Pequeno porte", icon: Heart },
];

export const helpOptions = [
  { label: "Ser voluntário", icon: HandHeart },
  { label: "Fazer doação", icon: Heart },
  { label: "Lar temporário", icon: HomeIcon },
  { label: "Parceiros", icon: Users },
];

export const pets = [
  {
    id: "Lola",
    name: "Lola",
    type: "Gato",
    species: "SRD",
    breed: "SRD",
    size: "Pequeno",
    age: "2 anos",
    sex: "Fêmea",
    city: "Recife",
    distance: "1,1 km",
    image: "/gato2.jpeg",
    badge: "Novo",
    tags: ["brincalhão", "sociável"],
    status: "Disponível",
    health: ["Vermifugado", "Primeira vacina aplicada", "Teste FIV/FeLV pendente"],
    history: "Resgatada com a ninhada em uma área residencial. Está em lar temporário e se adapta rápido a novas pessoas.",
    personality: "Curiosa, ativa e muito carinhoso depois que ganha confiança.",
  },
  {
    id: "luna",
    name: "Luna",
    type: "Cachorro",
    species: "Vira-lata",
    breed: "Vira-lata",
    size: "Médio",
    age: "1 ano",
    sex: "Fêmea",
    city: "Olinda",
    distance: "2,4 km",
    image: "/cachorrofemea1.png",
    badge: "Destaque",
    tags: ["calma", "ama crianças"],
    status: "Disponível",
    health: ["Vacinada", "Castrada", "Sem restrições conhecidas"],
    history: "Foi encontrada próxima a uma escola e acolhida por protetores locais.",
    personality: "Doce, companheira e tranquila em ambientes internos.",
  },
  {
    id: "thor",
    name: "Thor",
    type: "Cachorro",
    species: "Golden",
    breed: "Golden",
    size: "Médio",
    age: "2 anos",
    sex: "Macho",
    city: "Camaragibe",
    distance: "3,2 km",
    image: "/cachorro1.jpg",
    badge: "Sociável",
    tags: ["sociável", "brincalhão"],
    status: "Disponível",
    health: ["Vacinado", "Castrado", "Check-up recente"],
    history: "Chegou à ONG após mudança de endereço da família anterior.",
    personality: "Afetuoso, gosta de passeios e responde bem a rotina.",
  },
  {
    id: "bob",
    name: "Bob",
    type: "Cachorro",
    species: "Labrador",
    breed: "Labrador",
    size: "Médio",
    age: "2 anos",
    sex: "Macho",
    city: "Camaragibe",
    distance: "4,0 km",
    image: "/cachorromacho1.png",
    badge: "Novo",
    tags: ["leal", "ativo"],
    status: "Disponível",
    health: ["Vacinado", "Vermifugado", "Castrado"],
    history: "Resgatado em via pública e cuidado por uma rede de voluntários.",
    personality: "Cheio de energia, ideal para família que gosta de caminhar.",
  },
  {
    id: "bonito",
    name: "Bonito",
    type: "Gato",
    species: "SRD",
    breed: "SRD",
    size: "Pequeno",
    age: "7 meses",
    sex: "Macho",
    city: "Camaragibe",
    distance: "5,3 km",
    image: "/gatomacho1.png",
    badge: "Calmo",
    tags: ["calmo", "ideal para apartamento"],
    status: "Disponível",
    health: ["Castrado", "Vermifugado", "Vacina em dia"],
    history: "Nasceu em lar temporário e convive bem com outros gatos.",
    personality: "Observador, quietinho e muito apegado ao tutor.",
  },
  {
    id: "ze",
    name: "Zé",
    type: "Cachorro",
    species: "SRD",
    breed: "SRD",
    size: "Médio",
    age: "6 meses",
    sex: "Macho",
    city: "Camaragibe",
    distance: "5,8 km",
    image: "/cachorro2.jpg",
    badge: "Novo",
    tags: ["brincalhão", "sociável"],
    status: "Disponível",
    health: ["Vacinado", "Vermifugado", "Castracao a agendar"],
    history: "Filhote resgatado com irmãos e socializado em lar temporário.",
    personality: "Esperto, alegre e ótimo para quem quer acompanhar o crescimento.",
  },
  {
    id: "pipo",
    name: "Pipo",
    type: "Cachorro",
    species: "SRD",
    breed: "SRD",
    size: "Médio",
    age: "2 anos",
    sex: "Macho",
    city: "Camaragibe",
    distance: "6,1 km",
    image: "/cachorromacho2.jpg",
    badge: "Tranquilo",
    tags: ["calmo", "leal"],
    status: "Disponível",
    health: ["Castrado", "Vacinas em dia", "Sem medicação contínua"],
    history: "Acolhido após abandono e já passou por avaliação comportamental.",
    personality: "Tranquilo, companheiro e muito fiel.",
  },
  {
    id: "breu",
    name: "Breu",
    type: "Gato",
    species: "SRD",
    breed: "SRD",
    size: "Médio",
    age: "1 ano",
    sex: "Macho",
    city: "Camaragibe",
    distance: "6,4 km",
    image: "/gato1.jpg",
    badge: "Doce",
    tags: ["independente", "carinhoso"],
    status: "Disponível",
    health: ["Castrado", "Teste FIV/FeLV negativo", "Vacinado"],
    history: "Foi deixado em uma clínica parceira e está pronto para adoção.",
    personality: "Independente, mas adora carinho quando se sente seguro.",
  },
  {
    id: "listrado",
    name: "Listrado",
    type: "Gato",
    species: "SRD",
    breed: "SRD",
    size: "Médio",
    age: "1 ano",
    sex: "Macho",
    city: "Camaragibe",
    distance: "6,8 km",
    image: "/gato3.jpg",
    badge: "Apartamento",
    tags: ["ideal para apartamento", "calmo"],
    status: "Disponível",
    health: ["Vacinado", "Castrado", "Vermifugado"],
    history: "Resgatado ainda filhote e acostumado com rotina doméstica.",
    personality: "Calmo, dorminhoco e sociável com gatos tranquilos.",
  },
  {
    id: "ranzinza",
    name: "Ranzinza",
    type: "Gato",
    species: "SRD",
    breed: "SRD",
    size: "Médio",
    age: "8 meses",
    sex: "Macho",
    city: "Camaragibe",
    distance: "7,1 km",
    image: "/gatomacho2.png",
    badge: "Especial",
    tags: ["calmo", "observador"],
    status: "Disponível",
    health: ["Vermifugado", "Vacina em andamento", "Castracao a agendar"],
    history: "Ganhou o apelido pelo olhar sério, mas é muito dócil.",
    personality: "Reservado no começo, depois vira sombra do tutor.",
  },
  {
    id: "perola",
    name: "Pérola",
    type: "Cachorro",
    species: "Pitbull",
    breed: "Pitbull",
    size: "Médio",
    age: "2 anos",
    sex: "Fêmea",
    city: "Camaragibe",
    distance: "7,5 km",
    image: "/cachorrofemea2.jpg",
    badge: "Especial",
    tags: ["calma", "alerta, observadora"],
    status: "Disponível",
    health: ["Vacinada", "Vermifugada", "Castracao futura"],
    history: "Entregue porque tutor ia se mudar.",
    personality: "Esperta, ativa e muito apegada.",
  },
  {
    id: "thomas",
    name: "Thomas",
    type: "Cachorro",
    species: "Pastor",
    breed: "Pastor",
    size: "Grande",
    age: "2 anos",
    sex: "Macho",
    city: "Camaragibe",
    distance: "8,0 km",
    image: "/cachorromacho3.png",
    badge: "Protetor",
    tags: ["leal", "ama crianças"],
    status: "Disponível",
    health: ["Vacinado", "Castrado", "Acompanhamento de pele"],
    history: "Resgatado debilitado e recuperado com acompanhamento veterinário.",
    personality: "Leal, protetor e carinhoso com pessoas conhecidas.",
  },
];

export const orgs = [
  "Amor de Patas PE",
  "Abrigo Miados",
  "Protetores Recife",
  "Lar Temporário Azul",
  "Coração Animal",
  "Patinhas do Bem",
];

export const stories = [
  {
    title: "O Thor mudou nossa vida",
    text: "Ele chegou tímido e hoje espera todo mundo na porta.",
    author: "Juliana & Thor",
    tutorImage: "/pessoa1.png",
  },
  {
    title: "A Nina era o que faltava",
    text: "A casa ficou mais leve desde o primeiro ronronar.",
    author: "Raphael & Nina",
    tutorImage: "/pessoa3.png",
  },
  {
    title: "Bento trouxe alegria",
    text: "Cada passeio virou um pequeno ritual em família.",
    author: "Fernanda & Bento",
    tutorImage: "/pessoa2.png",
  },
];

export const faqs = [
  {
    question: "Como funciona o processo de adoção?",
    answer: "O MIAUmigos conecta adotantes e pets com base em compatibilidade de perfil, rotina e necessidades do animal. Após o match, o responsável pelo pet pode continuar o processo de avaliação e aprovação da adoção.",
  },
  {
    question: "O que é o Match Inteligente?",
    answer: "É o sistema que analisa informações do adotante e do pet para identificar maior compatibilidade entre ambos, ajudando a promover adoções mais responsáveis e duradouras.",
  },
  {
    question: "Como o MIAUmigos apoia ONGs e protetores?",
    answer: "A plataforma busca conectar adotantes, ONGs e protetores de forma segura e acessível, além de incentivar visibilidade, apoio e futuras iniciativas de doação para ajudar no cuidado dos animais.",
  },
  {
    question: "Quais documentos são necessários para efetuar uma doação?",
    answer: "Normalmente nome, CPF, contato e comprovante do pagamento quando a doação for financeira.",
  },
    {
    question: "Como funciona a verificação do adotante?",
    answer: "O sistema realiza uma validação básica de identidade, endereço e informações do ambiente para trazer mais segurança ao processo de adoção.",
  },
      {
    question: "Quais informações são analisadas no formulário?",
    answer: "São analisadas informações como rotina, espaço disponível, experiência com animais, presença de outros pets e estilo de vida do adotante.",
  },
    {
    question: "Posso cadastrar um pet para adoção?",
    answer: "Sim. ONGs e protetores independentes podem cadastrar animais diretamente na plataforma.",
  },
      {
    question: "O que acontece após a adoção?",
    answer: "Após a adoção, o sistema realiza check-ins automatizados durante os primeiros 90 dias para acompanhar a adaptação do pet e do adotante.",
  },
      {
    question: "O que são os check-ins de 90 dias?",
    answer: "São acompanhamentos automáticos feitos pela plataforma para ajudar no processo de adaptação e incentivar uma adoção responsável.",
  },
];
